# Apply the narrowly scoped backend fixes to the existing production image.
# Use an immutable local image ID for BASE_IMAGE when deploying.
ARG BASE_IMAGE=cvat/server:v2.64.0-farming
FROM ${BASE_IMAGE}
ARG REVISION
LABEL org.opencontainers.image.revision=${REVISION}
COPY --chown=django:django cvat/utils/sendfile.py /home/django/cvat/utils/sendfile.py
COPY --chown=django:django cvat/apps/engine/utils.py /home/django/cvat/apps/engine/utils.py
COPY --chown=django:django supervisord/server.conf /home/django/supervisord/server.conf
COPY cvat/nginx.conf /etc/nginx/nginx.conf
